---
engines:
  rubocop:
    enabled: true
  reek:
    enabled: true
  shellcheck:
    enabled: true
  brakeman:
    enabled: true

ratings:
  paths:
  - lib/**
  - "**/*.rb"

exclude_paths:
  - spec/**/*
  - "**/vendor/**/*"

