version: 2
jobs:
  build:
    working_directory: ~/kapost-bootstrapper
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run:
          name: Rspec
          command: bundle exec rspec --format documentation --color spec
